Add Artifact upload to actions
Signed-off-by: oguzkaganozt <oguzkaganozt@gmail.com>
Signed-off-by: Oguz Ozturk <oguzkaganozt@gmail.com>

diff --git a/.github/workflows/docker-build-and-push-main-self-hosted.yaml b/.github/workflows/docker-build-and-push-main-self-hosted.yaml
--- a/.github/workflows/docker-build-and-push-main-self-hosted.yaml
+++ b/.github/workflows/docker-build-and-push-main-self-hosted.yaml
@@ -1,17 +1,20 @@
 name: docker-build-and-push-main-self-hosted
 
 on:
+  push:
+    branches:
+      - main
   schedule:
     - cron: 0 0 1,15 * *
   workflow_dispatch:
     inputs:
       publish_packages:
-        description: 'Publish packages to GitHub Package Registry'
+        description: 'Publish packages to Registry(Check, if release)'
         required: true
         default: false
         type: boolean
       release_version:
-        description: 'Release version(If it is a release, specify the tag name for it)'
+        description: 'Release Version(Semver, if release)'
         required: false
         default: ''
         type: string
@@ -30,12 +33,21 @@ jobs:
             base_image_env: base_image
             lib_dir: aarch64
             setup-args: --no-nvidia
-            additional-tag-suffix: ""
+            additional-tag-suffix: -nocuda
           - name: cuda
             base_image_env: base_image
             lib_dir: aarch64
-            additional-tag-suffix: -cuda
+            additional-tag-suffix: ""
     steps:
+      - name: Check input conditions
+        run: |
+          if [[ ${{ github.event.inputs.publish_packages }} == 'true' ]]; then
+            if [[ -z "${{ github.event.inputs.release_version }}" ]]; then
+              echo "Error: 'release_version' is required when 'publish_packages' is true."
+              exit 1
+            fi
+          fi
+
       # https://github.com/actions/checkout/issues/211
       - name: Change permission of workspace
         run: |
